'use strict';
const CfmsModule = (() => {
  let d = null, step = 0, sc = null, test = null, tick = null, organise = false;
  const phases = [{id:'p5', label:'5 % ELS', min:1, times:[0,1]}, {id:'d1', label:'Décharge P1', min:0, times:['fin']}, {id:'p110', label:'110 % ELS', min:5, times:[0,1,2,3,4,5]}, {id:'df', label:'Décharge finale', min:0, times:['fin']}];
  function nouvelle(){d={type:'cfms',ref:'',version:1,codeProjet:'',client:'',nomProjet:'',lieu:'',entreprise:{},auto:'Non',createdAt:Date.now(),statut:'incomplet',cfms:{nbSc:26,nbL:2,nbT:2,equipement:{verin:'',aeff:'',compType:'Numérique',compNb:2,precision:'1/100 mm',compModele:'',pompe:'Manuelle',manoMax:700,manoModele:''},sousChamps:[]},essais:[]};step=0;renderSetup();AppNav.goto('screen-cfms');}
  async function reprendre(ref){d=await CAEKDB.getCampagne(ref);if(!d)return;d.cfms=d.cfms||{};d.cfms.sousChamps=d.cfms.sousChamps||[];step=0;renderSetup();AppNav.goto('screen-cfms');}
  async function renderSetup(){const ps=await Referentiel.getActiveProjets(), cs=await Referentiel.getActiveClients();setOpts('cfms-client',cs.map(x=>[x.id,x.nom]),'— Choisir un client —');setOpts('cfms-code-list',ps.map(x=>[x.codeProjet,`${x.codeProjet} — ${x.nomProjet||''}`]),'',true);val('cfms-code',d.codeProjet);val('cfms-nb-sc',d.cfms.nbSc);val('cfms-nb-l',d.cfms.nbL);val('cfms-nb-t',d.cfms.nbT);const e=d.cfms.equipement||{};['verin','aeff','comp-type','comp-nb','comp-precision','comp-modele','pompe','mano-max','mano-modele'].forEach(k=>val('cfms-'+k,e[key(k)]));showStep();if(d.codeProjet)await setProject(d.codeProjet);}
  function showStep(){['projet','campagne','equipement'].forEach((x,i)=>document.getElementById('cfms-step-'+x).hidden=i!==step);document.querySelectorAll('#cfms-stepper .step-item').forEach((x,i)=>{x.classList.toggle('is-active',i===step);x.classList.toggle('is-done',i<step)});document.getElementById('cfms-prev').hidden=!step;document.getElementById('cfms-next').textContent=step===2?'Créer la campagne':'Suivant';}
  async function onClient(){const id=val('cfms-client'), ps=id?await Referentiel.getProjetsOfClient(id):[];setOpts('cfms-projet',ps.map(x=>[x.codeProjet,`${x.nomProjet||x.codeProjet} — ${x.codeProjet}`]),'— Choisir un projet —');document.getElementById('cfms-projet').disabled=!id;}
  async function onProjet(){await setProject(val('cfms-projet'));}
  async function onCode(){const c=val('cfms-code').toUpperCase();if(c)await setProject(c);}
  async function setProject(code){const p=await Referentiel.getProjet(code);if(!p||p.actif===false){document.getElementById('cfms-proj-info').hidden=true;return;}d.codeProjet=p.codeProjet;d.client=p.client||'';d.nomProjet=p.nomProjet||'';d.lieu=[p.lieu,p.wilaya].filter(Boolean).join(' — ');d.auto=p.controle===false?'Oui':'Non';d.entreprise=d.auto==='Oui'?((await Referentiel.getEntrepriseForProjet(p))||{}):{};val('cfms-code',d.codeProjet);val('cfms-client',p.clientId||p.client);await onClient();val('cfms-projet',d.codeProjet);const b=document.getElementById('cfms-proj-info');b.hidden=false;b.innerHTML=`<div class="info-locked"><span class="info-label">Client</span><span>${esc(d.client)}</span></div><div class="info-locked"><span class="info-label">Projet</span><span>${esc(d.nomProjet)}</span></div><div class="info-locked"><span class="info-label">Code</span><span>${esc(d.codeProjet)}</span></div>`;}
  async function next(){if(step===0&&!d.codeProjet){alert('Choisissez un client puis un projet, ou introduisez le code projet.');return;}if(step===1){d.cfms.nbSc=+val('cfms-nb-sc');d.cfms.nbL=+val('cfms-nb-l');d.cfms.nbT=+val('cfms-nb-t');if(!d.cfms.nbSc||(!d.cfms.nbL&&!d.cfms.nbT)){alert('Définissez les sous-champs et au moins un essai.');return;}}if(step===2){const e=d.cfms.equipement={verin:val('cfms-verin'),aeff:val('cfms-aeff'),compType:val('cfms-comp-type'),compNb:+val('cfms-comp-nb'),precision:val('cfms-comp-precision'),compModele:val('cfms-comp-modele'),pompe:val('cfms-pompe'),manoMax:val('cfms-mano-max'),manoModele:val('cfms-mano-modele')};if(!e.verin||!(+e.aeff>0)||!(+e.manoMax>0)){alert('Complétez le vérin, sa surface et le manomètre.');return;}buildSc();await save();renderPlan();AppNav.goto('screen-cfms-plan');return;}step++;showStep();}
  function prev(){if(step){step--;showStep();}}
  function buildSc(){if(d.cfms.sousChamps.length)return;for(let i=1;i<=d.cfms.nbSc;i++)d.cfms.sousChamps.push({id:'SC'+String(i).padStart(2,'0'),lRest:d.cfms.nbL,tRest:d.cfms.nbT});}
  function renderPlan(){const f=d.cfms.sousChamps;document.getElementById('cfms-plan-info').innerHTML=`<div class="info-locked"><span class="info-label">${esc(d.codeProjet)}</span><span>${esc(d.nomProjet)}</span></div><div class="info-locked"><span class="info-label">Équipement</span><span>${esc(d.cfms.equipement.verin)}</span></div>`;document.getElementById('cfms-plan-hint').textContent=organise?'Glissez les sous-champs pour organiser le plan.':'Touchez un sous-champ pour commencer ou poursuivre un essai.';document.getElementById('cfms-grid').innerHTML=f.map((x,i)=>`<button class="cfms-cell ${(x.lRest+x.tRest)?'':'is-done'}" draggable="${organise}" data-sc="${i}"><strong>${x.id}</strong><span>L : ${x.lRest} · T : ${x.tRest}</span></button>`).join('');document.querySelectorAll('.cfms-cell').forEach(x=>{x.onclick=()=>{if(!organise)choose(+x.dataset.sc)};x.ondragstart=e=>e.dataTransfer.setData('text/plain',x.dataset.sc);x.ondragover=e=>e.preventDefault();x.ondrop=e=>{e.preventDefault();const a=+e.dataTransfer.getData('text/plain'),b=+x.dataset.sc;[f[a],f[b]]=[f[b],f[a]];renderPlan();save();}});}
  function choose(i){sc=i;const s=d.cfms.sousChamps[i];document.getElementById('cfms-choix-title').textContent=s.id;document.getElementById('cfms-choix-info').innerHTML=`<div class="info-locked"><span class="info-label">Restant</span><span>Latéral : ${s.lRest} · Traction : ${s.tRest}</span></div>`;['l','t'].forEach(k=>{const b=document.getElementById('cfms-start-'+k);b.disabled=!(k==='l'?s.lRest:s.tRest);});AppNav.goto('screen-cfms-choix');}
  function start(kind){test={n:(d.essais||[]).length+1,typeEssai:kind==='l'?'Horizontal':'Traction verticale',sousChamp:d.cfms.sousChamps[sc].id,date:date(),heure:time(),micropieu:{diam:'',long:'',table:'',rangee:'',position:'',gps:''},origine:{},phase:0,lectures:[],done:false};renderTest();AppNav.goto('screen-cfms-essai');}
  function renderTest(){const t=test;document.getElementById('cfms-essai-title').textContent=`${t.sousChamp} — ${t.typeEssai}`;document.getElementById('cfms-essai-info').textContent=`${d.codeProjet} · ${d.cfms.equipement.verin} · ${d.cfms.equipement.compNb} comparateur(s)`;val('cfms-date',t.date);val('cfms-heure',t.heure);['diam','long','table','rangee','position','gps'].forEach(k=>val('cfms-'+(k==='diam'?'diam':k==='long'?'long':k),t.micropieu[k]));document.getElementById('cfms-zero-l3-wrap').hidden=d.cfms.equipement.compNb<3;document.getElementById('cfms-runner').hidden=!t.started; if(t.started)runner();}
  function collectTest(){['diam','long','table','rangee','position','gps'].forEach(k=>test.micropieu[k]=val('cfms-'+(k==='diam'?'diam':k)));test.date=val('cfms-date');test.heure=val('cfms-heure');}
  function begin(){collectTest();if(!test.micropieu.diam||!test.micropieu.long){alert('Indiquez le diamètre et la longueur du micropieu.');return;}test.origine={l1:val('cfms-zero-l1'),l2:val('cfms-zero-l2'),l3:val('cfms-zero-l3')};if(!test.origine.l1||!test.origine.l2){alert('Saisissez les lectures initiales L1 et L2.');return;}test.started=true;test.phase=0;runner();document.getElementById('cfms-runner').hidden=false;save();}
  function runner(){const p=phases[test.phase];if(!p){finish();return;}const e=d.cfms.equipement, els=+promptSafe('ELS caractéristique de cet essai (kN)',test.els||'');if(!els)return;test.els=els;const force=p.id==='p5'?els*.05:p.id==='p110'?els*1.1:0, bar=force/(+e.aeff*.0001);const done=(test.lectures||[]).filter(x=>x.phase===p.id).map(x=>String(x.t));let pending=p.times.find(x=>!done.includes(String(x)));const elapsed=test.startedAt?Math.floor((Date.now()-test.startedAt)/1000):0;if(p.min&&test.startedAt){pending=p.times.find(x=>x<=Math.floor(elapsed/60)&&!done.includes(String(x)));}let h=`<div class="section-title">${p.label}</div><div class="cfms-target"><strong>${force.toFixed(2)} kN · ${bar.toFixed(1)} bar</strong><span>${p.min?fmt(elapsed)+' / '+p.min+':00':'Lecture de décharge'}</span></div>`;if(!test.startedAt&&p.min)h+='<button class="btn-primary" id="cfms-palier">✓ PALIER ATTEINT</button>';else if(p.min&&pending===undefined&&elapsed<p.min*60)h+='<p class="field-hint">Chrono en cours…</p>';else if(p.min&&pending===undefined)h+='<button class="btn-primary" id="cfms-next-phase">Décharger puis continuer</button>';else h+=readBox(p,pending);document.getElementById('cfms-runner').innerHTML=h;bindRunner(p,pending);clearInterval(tick);if(test.startedAt&&p.min)tick=setInterval(runner,1000);}
  function readBox(p,t){return `<div class="cfms-reading ${p.min?'is-alert':''}"><strong>Lecture t = ${t} min</strong><div class="field-row"><div class="field"><label>L1</label><input id="cfms-r-l1" inputmode="decimal"></div><div class="field"><label>L2</label><input id="cfms-r-l2" inputmode="decimal"></div></div>${d.cfms.equipement.compNb>=3?'<div class="field"><label>L3</label><input id="cfms-r-l3" inputmode="decimal"></div>':''}<button class="btn-primary" id="cfms-save-reading">Enregistrer la lecture</button></div>`;}
  function bindRunner(p,t){const a=document.getElementById('cfms-palier');if(a)a.onclick=()=>{test.startedAt=Date.now();runner()};const r=document.getElementById('cfms-save-reading');if(r)r.onclick=()=>{if(!val('cfms-r-l1')||!val('cfms-r-l2')){alert('L1 et L2 sont requis.');return;}test.lectures.push({phase:p.id,t,l1:val('cfms-r-l1'),l2:val('cfms-r-l2'),l3:val('cfms-r-l3'),ts:Date.now()});save();runner()};const n=document.getElementById('cfms-next-phase');if(n)n.onclick=()=>{test.phase++;test.startedAt=null;runner()};}
  function finish(){clearInterval(tick);test.done=true;d.essais.push(test);const s=d.cfms.sousChamps[sc];if(test.typeEssai==='Horizontal')s.lRest--;else s.tRest--;save().then(()=>{alert('Essai enregistré. Le plan de masse est mis à jour.');renderPlan();AppNav.goto('screen-cfms-plan')});}
  async function save(){if(!d.ref)d.ref=await ref();d.updatedAt=Date.now();d.operateur=AuthModule.currentName();await CAEKDB.saveCampagne(d);const c=await AuthModule.ensureValid();if(c.ok)await SyncModule.sendFiche('save',d.ref,'cfms',FicheModule.buildPayload(d));}
  async function ref(){try{const r=await ServerModule.nextRef(AuthModule.token(),'cfms',d.codeProjet);if(r&&r.ref)return r.ref}catch(_){}const n=await CAEKDB.nextNumero('cfms',d.codeProjet);return`QC/CFMS/${d.codeProjet}${String(n).padStart(2,'0')}`}
  function gps(){GpsHelper.locate('cfms-gps','cfms-essai-info','cfms-gps-btn')}function autosave(){if(d)save()}function key(k){return k.replace(/-([a-z])/g,(_,x)=>x.toUpperCase())}function val(id,v){const x=document.getElementById(id);if(v!==undefined)x.value=v==null?'':v;return(x.value||'').trim()}function setOpts(id,a,empty,list){const x=document.getElementById(id);if(list){x.innerHTML=a.map(z=>`<option value="${esc(z[0])}">${esc(z[1])}</option>`).join('');return;}x.innerHTML=`<option value="">${empty}</option>`+a.map(z=>`<option value="${esc(z[0])}">${esc(z[1])}</option>`).join('')}function date(){return new Date().toISOString().slice(0,10)}function time(){const x=new Date;return String(x.getHours()).padStart(2,'0')+':'+String(x.getMinutes()).padStart(2,'0')}function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function esc(x){return String(x||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}function promptSafe(a,b){return b||prompt(a,'')}
  function organiser(){organise=!organise;renderPlan();}
  return{nouvelle,reprendre,onClient,onProjet,onCode,next,prev,renderPlan,organiser,choose,start,begin,gps,autosave};
})();
